### ISSUE TITLE
FedML-IoT issues with runnnig on Jetson

### ISSUE THREAD

**Issue by rahulatulbhope** [FedML-AI/FedML#129]
Traceback (most recent call last):
  File "fedavg_jetson_nano_client.py", line 177, in <module>
    model_trainer.set_id(client_index)
NameError: name 'client_index' is not defined

Using the: fedavg_jetson_nano_client.py file.

python3 fedavg_jetson_nano_client.py --server_ip http://127.0.0.0:5000 --client_uuid '0'

The server is also running, the connection is made but the error is shown on the jetson side.

**Comment by chaoyanghe** [comment]
@zhang-tuo-pdf Hi Tuo, please check this platform issue.

**Comment by zhang-tuo-pdf** [comment]
Hi,

Thanks for using the FedML-IoT package. Seems like connection may not be made between the server and your jetson. For the program to be distributed implemented, you should let the server run the app.py file and the jetson run the client.py file. Also, if you are using the MQTT for communication, you could check the connection status via the MQTT portal. Please check the readme file at the following link. Also, you could write or edit your own program based on the layout in the following link.
https://github.com/FedML-AI/FedIoT/tree/main/experiments/Resberry_Pi

If this really helps you during your research or work, please remember to cite our newest FedIoT paper. https://arxiv.org/abs/2106.07976

**Comment by rahulatulbhope** [comment]
Hi,

Thanks a lot for the answer.

Had to add 'is_preprocessed' arg in the jetson code (also tried client_index = client_ID-1), changed the trainer = FedAVGTrainer(client_index,.... ) (added test_data_local_dict in the constructor call) line and changed my port to 1883, it worked. But faced a different issue later: 

Traceback (most recent call last):
  File "fedavg_jetson_nano_client.py", line 193, in <module>
    client_manager.start_training()
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAvgClientManager.py", line 48, in start_training
    self.__train()
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAvgClientManager.py", line 74, in __train
    weights, local_sample_num = self.trainer.train(self.round_idx)
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAVGTrainer.py", line 33, in train
    self.trainer.train(self.train_local, self.device, self.args)
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/MyModelTrainer.py", line 35, in train
    for batch_idx, (x, labels) in enumerate(train_data):
TypeError: 'NoneType' object is not iterable


Added, trainer.update_dataset(client_index) to get rid of that error, the model trained for 10 epochs on the jetson (I set it) then faced another issue (wrt model update in the server):

Traceback (most recent call last):
  File "fedavg_jetson_nano_client.py", line 195, in <module>
    client_manager.start_training()
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAvgClientManager.py", line 48, in start_training
    self.__train()
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAvgClientManager.py", line 75, in __train
    self.send_model_to_server(0, weights, local_sample_num)
  File "/home/rahulb/FedML/fedml_api/distributed/fedavg/FedAvgClientManager.py", line 70, in send_model_to_server
    self.send_message(message)
  File "/home/rahulb/FedML/fedml_core/distributed/client/client_manager.py", line 57, in send_message
    self.com_manager.send_message(msg)
  File "/home/rahulb/FedML/fedml_core/distributed/communication/mqtt/mqtt_comm_manager.py", line 120, in send_message
    self._client.publish(self._topic + str(self.client_id), payload=msg.to_json())
  File "/home/rahulb/FedML/fedml_core/distributed/communication/message.py", line 63, in to_json
    json_string = json.dumps(self.msg_params)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Tensor' is not JSON serializable

Tested this on 2 jetsons with my PC as the server, with UUID 0 and 1, but the dataset partition was similar in both (same loss on both jetsons). 

A video demonstration specifically for edge devices, if possible, would be very helpful.

**Comment by zhang-tuo-pdf** [comment]
Before doing this on the edge device, have you trained the training on the PC standalone before? Does it work smoothly on the CPU simulation?

**Comment by rahulatulbhope** [comment]
Yes, the standalone on my PC works fine. 

logs show training happening:
.
.
.
.
INFO:root:Local Training Epoch: 0 29963-th iters  Loss: 0.753548
INFO:root:Local Training Epoch: 0 29964-th iters  Loss: 0.511428
INFO:root:Local Training Epoch: 0 29965-th iters  Loss: 0.330766
INFO:root:Local Training Epoch: 0 29966-th iters  Loss: 1.531764
INFO:root:Local Training Epoch: 0 29967-th iters  Loss: 1.050786
INFO:root:Local Training Epoch: 0 29968-th iters  Loss: 0.369146
INFO:root:Local Training Epoch: 0 29969-th iters  Loss: 1.455213
INFO:root:Local Training Epoch: 0 29970-th iters  Loss: 0.380459
INFO:root:Local Training Epoch: 0 29971-th iters  Loss: 0.835266
INFO:root:Local Training Epoch: 0 29972-th iters  Loss: 0.539117
.
.
.
.

**Comment by rahulatulbhope** [comment]
Hi, I was able to get the program started, the weights transfer happens when I run both programs (app.py from FedML-Server and the fedavg_jetson_nano_client.py) on the same device (using FederatedMNIST and CNN). 

When I try 2 different devices, the weight transfer does not take place, it gets stuck in the time.sleep(100000). 

I also tried the fedavg setup with 1 server, 2 clients and 1 communication round (on the same device configuration), but the server does not stop even after weight transfer from both devices (used client per communication round = 2). As in the output like the standalone simulation is not shown even after the rounds are over.

I'm doing this for a project, could you please help me with the issues ?

Thanks.

**Comment by hdnhan** [comment]
Does anyone have any solution for this? I am still facing this problem?
Thanks!

**Comment by leigao97** [comment]
@hdnhan @rahulatulbhope Have you tried our current version FedIoT: https://github.com/FedML-AI/FedML/tree/master/iot We have migrated our code to the above link.

**Comment by fedml-dimitris** [comment]
@hdnhan @rahulatulbhope Please use the latest FedML version and let us know if the issue persists.
