### ISSUE TITLE
Can't download dataset such as cora and  PubMed  by run sampleEgonetworks.py  in /FedGraphNN-main/data_preprocessing/ego_networks

### ISSUE THREAD

**Issue by ZeLiGuan** [FedML-AI/FedML#164]
I can downl dataset by url ，but i don't know how can i use  cora.npz direct

The error like this:

/FedGraphNN-main/data_preprocessing/ego_networks$ python3 sampleEgonetworks.py --path ./../../data/ego-networks/ --data cora --ego_number 1000 --hop_number 2
Downloading https://github.com/abojchevski/graph2gauss/raw/master/data/cora.npz
Traceback (most recent call last):
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sampleEgonetworks.py", line 135, in <module>
    subgraphs, num_graphs, num_features, num_labels = get_data(args.path, args.data, args.ego_number, args.hop_number, args.sampling)
  File "sampleEgonetworks.py", line 93, in get_data
    pyg_dataset = CitationFull(path, data)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/datasets/citation_full.py", line 38, in __init__
    super().__init__(root, transform, pre_transform)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 85, in __init__
    self._download()
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 146, in _download
    self.download()
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/datasets/citation_full.py", line 58, in download
    download_url(self.url.format(self.name), self.raw_dir)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/site-packages/torch_geometric/data/download.py", line 34, in download_url
    data = urllib.request.urlopen(url, context=context)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/gzl/anaconda3/envs/fedgraphnn/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by chaoyanghe** [comment]
@emirceyani Please check this problem.

**Comment by fedml-dimitris** [comment]
@emirceyani Can you please give it a shot using the latest fedml-dev https://github.com/FedML-AI/FedML/tree/dev/v0.7.0
