### ISSUE TITLE
Weights&biases

### ISSUE THREAD

**Issue by Yang-cpu502** [FedML-AI/FedML#179]
When I look at the result display graph in Weights&biases, it shows that the operation failed, check the reason, is it because of insufficient memory?

wandb: Run data is saved locally in /home/hadoop/下载/FedML-master/fedml_experiments/standalone/fedavg/wandb/run-20220408_112803-2ots05l0
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run FedAVG-r200-e1-lr0.03
wandb: ⭐️ View project at https://wandb.ai/yangbinbing/fedml
wandb: 🚀 View run at https://wandb.ai/yangbinbing/fedml/runs/2ots05l0
INFO:root:load_data. dataset_name = mnist
Traceback (most recent call last):
  File "./main_fedavg.py", line 305, in <module>
    dataset = load_data(args, args.dataset)
  File "./main_fedavg.py", line 110, in load_data
    class_num = load_partition_data_mnist(args.batch_size)
  File "/home/hadoop/下载/FedML-master/fedml_api/data_preprocessing/MNIST/data_loader.py", line 90, in load_partition_data_mnist
    users, groups, train_data, test_data = read_data(train_path, test_path)
  File "/home/hadoop/下载/FedML-master/fedml_api/data_preprocessing/MNIST/data_loader.py", line 33, in read_data
    cdata = json.load(inf)
  File "/home/hadoop/miniconda/envs/fedml/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/hadoop/miniconda/envs/fedml/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced FedAVG-r200-e1-lr0.03: https://wandb.ai/yangbinbing/fedml/runs/2ots05l0
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220408_112803-2ots05l0/logs

**Comment by chaoyanghe** [comment]
@Yang-cpu502 Please check your memory cost when running.

**Comment by chaoyanghe** [comment]
@Yang-cpu502 is your issue solved?

**Comment by fedml-dimitris** [comment]
Closing due to inactivity.
