### ISSUE TITLE
FedML login failed at Ubuntu 20.04 

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#197]
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~/sourcecode/FedML_startup/FedML/python$ fedml login 11
Argument for account Id: 11
Argument for version: release
sh: 1: /home/chaoyanghe/.local/lib/python3.8/site-packages/fedml/cli/edge_deployment/run.sh: not found
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~/sourcecode/FedML_startup/FedML/python$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~/sourcecode/FedML_startup/FedML/python$

**Comment by chaoyanghe** [comment]
(fedml) chaoyanghe@Chaoyangs-MBP python % fedml login 11
/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/bin/fedml", line 33, in <module>
    sys.exit(load_entry_point('fedml==0.7.7', 'console_scripts', 'fedml')())
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/bin/fedml", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/fedml-0.7.7-py3.7.egg/fedml/__init__.py", line 7, in <module>
    from fedml.mlops import MLOpsRuntimeLog
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/fedml-0.7.7-py3.7.egg/fedml/mlops/__init__.py", line 1, in <module>
    from .mlops_metrics import MLOpsMetrics
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/fedml-0.7.7-py3.7.egg/fedml/mlops/mlops_metrics.py", line 4, in <module>
    from .system_stats import SysStats
  File "/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/fedml-0.7.7-py3.7.egg/fedml/mlops/system_stats.py", line 5, in <module>
    from pynvml import NVML_TEMPERATURE_GPU
ImportError: cannot import name 'NVML_TEMPERATURE_GPU' from 'pynvml' (/Users/chaoyanghe/opt/anaconda3/envs/fedml/lib/python3.7/site-packages/wandb/vendor/pynvml/__init__.py)
(fedml) chaoyanghe@Chaoyangs-MBP python %

**Comment by chaoyanghe** [comment]
(base) chaoyanghe@Chaoyangs-MBP FedML_product % fedml login 11          
Traceback (most recent call last):
  File "/Users/chaoyanghe/opt/anaconda3/bin/fedml", line 5, in <module>
    from fedml.cli.cli import cli
  File "/Users/chaoyanghe/opt/anaconda3/lib/python3.8/site-packages/fedml/cli/cli.py", line 6, in <module>
    from .edge_deployment.login import login_with_docker_mode
ModuleNotFoundError: No module named 'fedml.cli.edge_deployment'
(base) chaoyanghe@Chaoyangs-MBP FedML_product %

**Comment by chaoyanghe** [comment]
```
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~/sourcecode/FedML_startup/FedML/python$ fedml login 11
Argument for account Id: 11
Argument for version: release
Deployment version: release
OS Name: Linux
current dir: /home/chaoyanghe
The FedML client agent is being deployed, please wait for a moment...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Using docker daemon mode
.........................
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=public.ecr.aws%2Fx6k8q1x9%2Ffedml-client-agent&tag=dev": dial unix /var/run/docker.sock: connect: permission denied
Congratulations, you have deployed the FedML client agent successfully!
Your device id is 0xb5282c8932b8. You may review the device in the MLOps edge device list.
--------------------------------------------------------------------------------------------
Now the system will post-process to pull the FedML client docker image to your localhost.
You may do other things to start your FedML flow. (User Guide: https://doc.fedml.ai)
You just need to keep this window not closed until the processing is finished.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=public.ecr.aws%2Fx6k8q1x9%2Ffedml-cross-silo-cpu&tag=dev": dial unix /var/run/docker.sock: connect: permission denied
Great, you have succeeded to complete all the running processes.

```
