### ISSUE TITLE
[FedML][Cross-silo] sys_stat error on Windows env

### ISSUE THREAD

**Issue by leigao97** [FedML-AI/FedML#307]
One user opened this issue: https://github.com/FedML-AI/FedML/issues/294
The following is the reproduced bug:

Traceback (most recent call last):

  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\core\distributed\communication\mqtt_s3\mqtt_s3_multi_clients_comm_manager.py", line 153, in _on_connect
    self._on_connect_impl(client, userdata, flags, rc)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\core\distributed\communication\mqtt_s3\mqtt_s3_multi_clients_comm_manager.py", line 144, in _on_connect_impl
    self._notify_connection_ready()
    observer.receive_message(msg_type, msg_params)
    handler_callback_func(msg_params)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\cross_silo\horizontal\fedml_client_manager.py", line 63, in handle_message_connection_ready
    self.sys_stats_process.start()
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'botocore.client.S3'>: attribute lookup S3 on botocore.client failed

[FedML-Client(1) @device-id-1] [Mon, 20 Jun 2022 12:20:28] [INFO] [mqtt_s3_multi_clients_comm_manager.py:162:_on_disconnect] mqtt_s3.on_disconnect: disconnection returned result 0, user data None
[FedML-Client(1) @device-id-1] [Mon, 20 Jun 2022 12:20:28] [INFO] [mqtt_s3_status_manager.py:82:_on_disconnect] mqtt_s3.on_disconnect: disconnection returned result 0, user data None
PS C:\Users\Lei\Downloads\FedML\python\examples\cross_silo\mqtt_s3_fedavg_mnist_lr_example\custum_data_and_model> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by leigao97** [comment]
One user opened this issue: https://github.com/FedML-AI/FedML/issues/294
The following is the reproduced bug:

Traceback (most recent call last):

  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\core\distributed\communication\mqtt_s3\mqtt_s3_multi_clients_comm_manager.py", line 153, in _on_connect
    self._on_connect_impl(client, userdata, flags, rc)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\core\distributed\communication\mqtt_s3\mqtt_s3_multi_clients_comm_manager.py", line 144, in _on_connect_impl
    self._notify_connection_ready()
    observer.receive_message(msg_type, msg_params)
    handler_callback_func(msg_params)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\site-packages\fedml\cross_silo\horizontal\fedml_client_manager.py", line 63, in handle_message_connection_ready
    self.sys_stats_process.start()
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'botocore.client.S3'>: attribute lookup S3 on botocore.client failed

[FedML-Client(1) @device-id-1] [Mon, 20 Jun 2022 12:20:28] [INFO] [mqtt_s3_multi_clients_comm_manager.py:162:_on_disconnect] mqtt_s3.on_disconnect: disconnection returned result 0, user data None
[FedML-Client(1) @device-id-1] [Mon, 20 Jun 2022 12:20:28] [INFO] [mqtt_s3_status_manager.py:82:_on_disconnect] mqtt_s3.on_disconnect: disconnection returned result 0, user data None
PS C:\Users\Lei\Downloads\FedML\python\examples\cross_silo\mqtt_s3_fedavg_mnist_lr_example\custum_data_and_model> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Lei\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by chaoyanghe** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/7238845/176719843-404f5c27-38e0-48ed-b3fb-0e593ed1afeb.png">

**Comment by chaoyanghe** [comment]
https://github.com/Koed00/django-q/issues/424
