### ISSUE TITLE
fed_CIFAR100 dataset loading error

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#36]
Traceback (most recent call last):
  File "./main_fedavg.py", line 163, in <module>
    dataset = load_data(args, args.dataset)
  File "./main_fedavg.py", line 109, in load_data
    class_num = load_partition_data_federated_cifar100(args.dataset, args.data_dir, batch_size=args.batch_size)
  File "/home/chaoyanghe/sourcecode/fedml.ai/fedml_api/data_preprocessing/fed_cifar100/data_loader.py", line 115, in load_partition_data_federated_cifar100
    train_data_local, test_data_local = get_dataloader(dataset, data_dir, batch_size, batch_size, client_idx)
  File "/home/chaoyanghe/sourcecode/fedml.ai/fedml_api/data_preprocessing/fed_cifar100/data_loader.py", line 54, in get_dataloader
    test_dl = data.DataLoader(dataset = test_ds, batch_size=test_bs, shuffle = True, drop_last = False)
  File "/home/chaoyanghe/miniconda/envs/fedml/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/chaoyanghe/miniconda/envs/fedml/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 96, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by chaoyanghe** [comment]
fixed
