### ISSUE TITLE
‘’windows10 simulation error ‘’ FileNotFoundError: [WinError 2] when running ‘’torch_fedavg_mnist_lr_step_by_step_example.py‘’

### ISSUE THREAD

**Issue by TongGeTT** [FedML-AI/FedML#433]
Hello：
       **when I run the file mentioned in the title which is in the path of ‘FedML\python\examples\simulation\sp_fedavg_mnist_lr_example’， I got the following results：**

======== FedML (https://fedml.ai) ========
FedML version: 0.7.282
Execution path:D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\__init__.py

======== Running Environment ========
OS: Windows-10-10.0.19041-SP0
Hardware: AMD64
Python version: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
PyTorch version: 1.12.0+cpu
MPI4py is NOT installed

======== CPU Configuration ========
The CPU usage is : 0%
Available CPU Memory: 10.4 G / 15.855926513671875G

======== GPU Configuration ========
No GPU devices
[]
args.client_id_list = None
training_type != FEDML_TRAINING_PLATFORM_CROSS_DEVICE and training_type != FEDML_TRAINING_PLATFORM_CROSS_SILO

Process finished with exit code 1

      **However， I have a RTX 3060Ti on my machine， I have no idea why it shows No GPU devices。 And I have installed MPI4py, but it shows I haven't**

      **What‘s more， I got the following error information：**

Traceback (most recent call last):
  File "G:/Desktop/FedML/python/examples/simulation/sp_fedavg_mnist_lr_example/torch_fedavg_mnist_lr_step_by_step_example.py", line 7, in <module>
    args = fedml.init()
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\__init__.py", line 93, in init
    mlops.init(args)
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\mlops\__init__.py", line 9, in init
    mlops.init(args)
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\core\mlops\__init__.py", line 95, in init
    MLOpsStore.mlops_bind_result = bind_simulation_device(args, api_key, args.config_version)
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\core\mlops\__init__.py", line 558, in bind_simulation_device
    setattr(args, "device_id", FedMLServerRunner.get_device_id())
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\cli\server_deployment\server_runner.py", line 910, in get_device_id
    device_id = str(GetUUID())
  File "D:\Anaconda\3.8\envs\fedml.new\lib\site-packages\fedml\cli\server_deployment\server_runner.py", line 905, in GetUUID
    uuid = str(subprocess.check_output(cmd))
  File "D:\Anaconda\3.8\envs\fedml.new\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "D:\Anaconda\3.8\envs\fedml.new\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\3.8\envs\fedml.new\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\3.8\envs\fedml.new\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

      **I have no idea how to solve these problems， so I come here to look for helps**

**Comment by alex-liang-kh** [comment]
Please update the code to 0.7.230, it should be fixed.

**Comment by chaoyanghe** [comment]
@TongGeTT Hi, is this issue solved on your side?

**Comment by fedml-dimitris** [comment]
Closing this, since the issue has been resolved in version 0.7.287.
