### ISSUE TITLE
errors after "fedml login 302 -s" on Ubuntu 20.04

### ISSUE THREAD

**Issue by chaoyanghe** [FedML-AI/FedML#778]

**Comment by chaoyanghe** [comment]
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ fedml login 302 -s
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ [FedML-Server(0) @device-id-13416] [Wed, 15 Feb 2023 11:54:57] [INFO] [server_login.py:110:__login_as_edge_server_and_agent] login: unique_device_id = 0x87e6a10d8828@Linux.Edge.Server
[FedML-Server(0) @device-id-13416] [Wed, 15 Feb 2023 11:54:57] [INFO] [server_login.py:111:__login_as_edge_server_and_agent] login: server_id = 13416
[FedML-Server(0) @device-id-13416] [Wed, 15 Feb 2023 11:54:57] [INFO] [server_runner.py:803:setup_client_mqtt_mgr] client agent config: mqtt.fedml.ai,1883
[FedML-Server(0) @device-id-13416] [Wed, 15 Feb 2023 11:54:57] [INFO] [mlops_metrics.py:238:common_report_server_training_status] report_server_training_status. msg = {'run_id': 0, 'edge_id': 13416, 'status': 'IDLE', 'role': 'normal'}
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fedml'

Congratulations, you have logged into the FedML MLOps platform successfully!
Your server unique device id is 0x87e6a10d8828@Linux.Edge.Server

**Comment by chaoyanghe** [comment]
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ pip uninstall fedml
Found existing installation: fedml 0.7.500
Uninstalling fedml-0.7.500:
  Would remove:
    /home/chaoyanghe/miniconda/envs/fedml/bin/fedml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml-aggregator-data-pv.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml-aggregator-data-pvc.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml-server-deployment.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml-server-svc.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/fedml_config.yaml
    /home/chaoyanghe/miniconda/envs/fedml/fedml/open-dev.fedml.ai_bundle.crt
    /home/chaoyanghe/miniconda/envs/fedml/fedml/open-release.fedml.ai_bundle.crt
    /home/chaoyanghe/miniconda/envs/fedml/fedml/open-root-ca.crt
    /home/chaoyanghe/miniconda/envs/fedml/fedml/open-test.fedml.ai_bundle.crt
    /home/chaoyanghe/miniconda/envs/fedml/lib/python3.8/site-packages/examples/*
    /home/chaoyanghe/miniconda/envs/fedml/lib/python3.8/site-packages/fedml-0.7.500.dist-info/*
    /home/chaoyanghe/miniconda/envs/fedml/lib/python3.8/site-packages/fedml/*
    /home/chaoyanghe/miniconda/envs/fedml/lib/python3.8/site-packages/tests/*
Proceed (Y/n)? Y
  Successfully uninstalled fedml-0.7.500
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ fedml login 302 -s^C
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ pip install -U fedml
Collecting fedml
  Using cached fedml-0.7.500-py2.py3-none-any.whl (918 kB)
Requirement already satisfied: spacy in ./.local/lib/python3.8/site-packages (from fedml) (3.5.0)
Requirement already satisfied: PyYAML in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (5.4.1)
Requirement already satisfied: boto3 in ./.local/lib/python3.8/site-packages (from fedml) (1.20.38)
Requirement already satisfied: pandas in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (1.5.0)
Requirement already satisfied: scikit-learn in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (1.1.2)
Requirement already satisfied: aiohttp>=3.8.1 in ./.local/lib/python3.8/site-packages (from fedml) (3.8.4)
Requirement already satisfied: ntplib in ./.local/lib/python3.8/site-packages (from fedml) (0.4.0)
Requirement already satisfied: redis in ./.local/lib/python3.8/site-packages (from fedml) (4.5.1)
Requirement already satisfied: wget in ./.local/lib/python3.8/site-packages (from fedml) (3.2)
Requirement already satisfied: typing-extensions==4.4.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (4.4.0)
Requirement already satisfied: click in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (8.1.3)
Requirement already satisfied: attrdict in ./.local/lib/python3.8/site-packages (from fedml) (2.0.1)
Requirement already satisfied: nvidia-ml-py3 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (7.352.0)
Requirement already satisfied: attrs in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (22.2.0)
Requirement already satisfied: torchvision in ./.local/lib/python3.8/site-packages (from fedml) (0.12.0)
Requirement already satisfied: smart-open==5.2.1 in ./.local/lib/python3.8/site-packages (from fedml) (5.2.1)
Requirement already satisfied: gensim in ./.local/lib/python3.8/site-packages (from fedml) (4.3.0)
Requirement already satisfied: httpx in ./.local/lib/python3.8/site-packages (from fedml) (0.23.3)
Requirement already satisfied: tqdm in ./.local/lib/python3.8/site-packages (from fedml) (4.64.0)
Requirement already satisfied: matplotlib in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (3.6.0)
Requirement already satisfied: wandb==0.13.2 in ./.local/lib/python3.8/site-packages (from fedml) (0.13.2)
Requirement already satisfied: fastapi==0.92.0 in ./.local/lib/python3.8/site-packages (from fedml) (0.92.0)
Requirement already satisfied: eciespy in ./.local/lib/python3.8/site-packages (from fedml) (0.3.13)
Requirement already satisfied: numpy==1.21 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (1.21.0)
Requirement already satisfied: geventhttpclient<=2.0.2,>=1.4.4 in ./.local/lib/python3.8/site-packages (from fedml) (2.0.2)
Requirement already satisfied: pynvml in ./.local/lib/python3.8/site-packages (from fedml) (11.4.1)
Requirement already satisfied: multiprocess in ./.local/lib/python3.8/site-packages (from fedml) (0.70.14)
Requirement already satisfied: h5py in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (3.7.0)
Requirement already satisfied: python-rapidjson>=0.9.1 in ./.local/lib/python3.8/site-packages (from fedml) (1.9)
Requirement already satisfied: paho-mqtt in ./.local/lib/python3.8/site-packages (from fedml) (1.6.1)
Requirement already satisfied: networkx in ./.local/lib/python3.8/site-packages (from fedml) (2.8)
Requirement already satisfied: dill in ./.local/lib/python3.8/site-packages (from fedml) (0.3.6)
Requirement already satisfied: torch in ./.local/lib/python3.8/site-packages (from fedml) (1.11.0)
Requirement already satisfied: PyNaCl in ./miniconda/envs/fedml/lib/python3.8/site-packages (from fedml) (1.5.0)
Requirement already satisfied: uvicorn in ./.local/lib/python3.8/site-packages (from fedml) (0.20.0)
Requirement already satisfied: tritonclient in ./.local/lib/python3.8/site-packages (from fedml) (2.30.0)
Requirement already satisfied: starlette<0.26.0,>=0.25.0 in ./.local/lib/python3.8/site-packages (from fastapi==0.92.0->fedml) (0.25.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in ./.local/lib/python3.8/site-packages (from fastapi==0.92.0->fedml) (1.10.4)
Requirement already satisfied: shortuuid>=0.5.0 in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (1.0.8)
Requirement already satisfied: protobuf<4.0dev,>=3.12.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (3.19.6)
Requirement already satisfied: requests<3,>=2.0.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (2.28.1)
Requirement already satisfied: sentry-sdk>=1.0.0 in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (1.5.10)
Requirement already satisfied: setproctitle in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (1.2.3)
Requirement already satisfied: pathtools in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (0.1.2)
Requirement already satisfied: setuptools in ./miniconda/envs/fedml/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (63.4.1)
Requirement already satisfied: docker-pycreds>=0.4.0 in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (0.4.0)
Requirement already satisfied: psutil>=5.0.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (5.9.2)
Requirement already satisfied: six>=1.13.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (1.16.0)
Requirement already satisfied: GitPython>=1.0.0 in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (3.1.27)
Requirement already satisfied: promise<3,>=2.0 in ./.local/lib/python3.8/site-packages (from wandb==0.13.2->fedml) (2.3)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.local/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./.local/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./.local/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (1.8.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from aiohttp>=3.8.1->fedml) (2.1.1)
Requirement already satisfied: brotli in ./.local/lib/python3.8/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->fedml) (1.0.9)
Requirement already satisfied: certifi in ./miniconda/envs/fedml/lib/python3.8/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->fedml) (2022.6.15)
Requirement already satisfied: gevent>=0.13 in ./.local/lib/python3.8/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->fedml) (22.10.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./.local/lib/python3.8/site-packages (from boto3->fedml) (0.10.0)
Requirement already satisfied: botocore<1.24.0,>=1.23.38 in ./.local/lib/python3.8/site-packages (from boto3->fedml) (1.23.38)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in ./.local/lib/python3.8/site-packages (from boto3->fedml) (0.5.0)
Requirement already satisfied: pycryptodome<4.0.0,>=3.15.0 in ./.local/lib/python3.8/site-packages (from eciespy->fedml) (3.17)
Requirement already satisfied: eth-keys<0.5.0,>=0.4.0 in ./.local/lib/python3.8/site-packages (from eciespy->fedml) (0.4.0)
Requirement already satisfied: coincurve<18,>=13 in ./.local/lib/python3.8/site-packages (from eciespy->fedml) (17.0.0)
Requirement already satisfied: FuzzyTM>=0.4.0 in ./.local/lib/python3.8/site-packages (from gensim->fedml) (2.0.5)
Requirement already satisfied: scipy>=1.7.0 in ./.local/lib/python3.8/site-packages (from gensim->fedml) (1.10.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in ./.local/lib/python3.8/site-packages (from httpx->fedml) (1.5.0)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in ./.local/lib/python3.8/site-packages (from httpx->fedml) (0.16.3)
Requirement already satisfied: sniffio in ./.local/lib/python3.8/site-packages (from httpx->fedml) (1.3.0)
Requirement already satisfied: pillow>=6.2.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (4.37.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (1.0.5)
Requirement already satisfied: packaging>=20.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from matplotlib->fedml) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from pandas->fedml) (2022.2.1)
Requirement already satisfied: cffi>=1.4.1 in ./.local/lib/python3.8/site-packages (from PyNaCl->fedml) (1.15.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from scikit-learn->fedml) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from scikit-learn->fedml) (1.2.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (2.0.8)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (3.0.8)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (3.0.12)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (8.1.7)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (0.7.0)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (1.1.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (1.0.9)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (2.4.5)
Requirement already satisfied: pathy>=0.10.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (0.10.1)
Requirement already satisfied: jinja2 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from spacy->fedml) (3.1.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (3.3.0)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.local/lib/python3.8/site-packages (from spacy->fedml) (1.0.4)
Requirement already satisfied: h11>=0.8 in ./.local/lib/python3.8/site-packages (from uvicorn->fedml) (0.14.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in ./.local/lib/python3.8/site-packages (from botocore<1.24.0,>=1.23.38->boto3->fedml) (1.26.9)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi>=1.4.1->PyNaCl->fedml) (2.21)
Requirement already satisfied: asn1crypto in ./.local/lib/python3.8/site-packages (from coincurve<18,>=13->eciespy->fedml) (1.5.1)
Requirement already satisfied: eth-typing<4,>=3.0.0 in ./.local/lib/python3.8/site-packages (from eth-keys<0.5.0,>=0.4.0->eciespy->fedml) (3.2.0)
Requirement already satisfied: eth-utils<3.0.0,>=2.0.0 in ./.local/lib/python3.8/site-packages (from eth-keys<0.5.0,>=0.4.0->eciespy->fedml) (2.1.0)
Requirement already satisfied: pyfume in ./.local/lib/python3.8/site-packages (from FuzzyTM>=0.4.0->gensim->fedml) (0.2.25)
Requirement already satisfied: zope.interface in ./.local/lib/python3.8/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->fedml) (5.5.2)
Requirement already satisfied: zope.event in ./.local/lib/python3.8/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->fedml) (4.6)
Requirement already satisfied: greenlet>=2.0.0 in ./.local/lib/python3.8/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->fedml) (2.0.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.local/lib/python3.8/site-packages (from GitPython>=1.0.0->wandb==0.13.2->fedml) (4.0.9)
Requirement already satisfied: anyio<5.0,>=3.0 in ./.local/lib/python3.8/site-packages (from httpcore<0.17.0,>=0.15.0->httpx->fedml) (3.6.2)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb==0.13.2->fedml) (3.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in ./.local/lib/python3.8/site-packages (from thinc<8.2.0,>=8.1.0->spacy->fedml) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.local/lib/python3.8/site-packages (from thinc<8.2.0,>=8.1.0->spacy->fedml) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniconda/envs/fedml/lib/python3.8/site-packages (from jinja2->spacy->fedml) (2.1.1)
Requirement already satisfied: eth-hash>=0.3.1 in ./.local/lib/python3.8/site-packages (from eth-utils<3.0.0,>=2.0.0->eth-keys<0.5.0,>=0.4.0->eciespy->fedml) (0.5.1)
Requirement already satisfied: cytoolz>=0.10.1 in ./.local/lib/python3.8/site-packages (from eth-utils<3.0.0,>=2.0.0->eth-keys<0.5.0,>=0.4.0->eciespy->fedml) (0.12.1)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb==0.13.2->fedml) (5.0.0)
Requirement already satisfied: fst-pso in ./.local/lib/python3.8/site-packages (from pyfume->FuzzyTM>=0.4.0->gensim->fedml) (1.8.1)
Requirement already satisfied: simpful in ./.local/lib/python3.8/site-packages (from pyfume->FuzzyTM>=0.4.0->gensim->fedml) (2.9.0)
Requirement already satisfied: toolz>=0.8.0 in ./.local/lib/python3.8/site-packages (from cytoolz>=0.10.1->eth-utils<3.0.0,>=2.0.0->eth-keys<0.5.0,>=0.4.0->eciespy->fedml) (0.12.0)
Requirement already satisfied: miniful in ./.local/lib/python3.8/site-packages (from fst-pso->pyfume->FuzzyTM>=0.4.0->gensim->fedml) (0.0.6)
Installing collected packages: fedml
Successfully installed fedml-0.7.500
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ fedml login 302 -s
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fedml'
chaoyanghe@ChaoyangHe-GPU-RTX2080Tix4:~$ [FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [server_login.py:110:__login_as_edge_server_and_agent] login: unique_device_id = 0x87e6a10d8828@Linux.Edge.Server
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [server_login.py:111:__login_as_edge_server_and_agent] login: server_id = 13416
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [mqtt_manager.py:60:init_connect] MQTT Connection timeout: 15, client id FedML_ServerAgent_Daemon_0x87e6a10d8828_ID.
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [server_runner.py:908:setup_client_mqtt_mgr] client agent config: mqtt.fedml.ai,1883
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [mqtt_manager.py:60:init_connect] MQTT Connection timeout: 15, client id FedML_ServerAgent_Metrics_0x87e6a10d8828_527788_d99f7acf-ae88-4a0f-a68b-d33a278882f0_ID.
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [mlops_metrics.py:238:common_report_server_training_status] report_server_training_status. msg = {'run_id': 0, 'edge_id': 13416, 'status': 'IDLE', 'role': 'normal'}
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [mqtt_manager.py:280:check_connection] MQTT client id FedML_ServerAgent_Metrics_0x87e6a10d8828_527788_d99f7acf-ae88-4a0f-a68b-d33a278882f0_ID, waiting to connect to MQTT server...
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:17] [INFO] [mqtt_manager.py:127:on_connect] MQTT Connection is OK, client id FedML_ServerAgent_Metrics_0x87e6a10d8828_527788_d99f7acf-ae88-4a0f-a68b-d33a278882f0_ID.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/chaoyanghe/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fedml'
[FedML-Server(0) @device-id-13416] [Sun, 26 Feb 2023 19:30:18] [INFO] [mqtt_manager.py:127:on_connect] MQTT Connection is OK, client id FedML_ServerAgent_Daemon_0x87e6a10d8828_ID.

Congratulations, you have logged into the FedML MLOps platform successfully!
Your server unique device id is 0x87e6a10d8828@Linux.Edge.Server
