### ISSUE TITLE
MQTT connect exception: timed out

### ISSUE THREAD

**Issue by GivralNguyen** [FedML-AI/FedML#804]
Hi, when i tried to run anything using fedml, this error occurs:
======== Network Connection Checking ========
The connection to https://open.fedml.ai is OK.
The connection to AWS S3 is OK.
MQTT connect exception: timed out
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/site-packages/fedml/cli/edge_deployment/client_diagnosis.py", line 79, in check_mqtt_connection
    mqtt_mgr.connect()
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/site-packages/fedml/core/distributed/communication/mqtt/mqtt_manager.py", line 70, in connect
    self._client.connect(self._host, self._port, self.keepalive_time)
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/home/ubuntu/miniconda3/envs/pytorchpython39/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
socket.timeout: timed out
Is there any possible fix to this?

**Comment by fedml-alex** [comment]
Please update to latest version: pip install -U fedml
